version: "3"
services:
  # nginx:
  #   container_name: paper-nginx
  #   image: latest123/paper-nginx
  #   restart: always
  #   build:
  #     context: ../paper-web-app
  #     dockerfile: ./docker/dev/Dockerfile
    # volumes:
    #   - ./data/certbot/conf:/etc/letsencrypt
    #   - ./data/certbot/www:/var/www/certbot
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  paper-web-app:
    container_name: paper-web-app
    image: latest123/paper-web-app
    restart: always
    build:
      context: ../paper-web-app
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8090:80"
  paper-ebook-admin-be:
    container_name: paper-ebook-admin-be
    image: latest123/paper-ebook-admin-be
    restart: always
    build:
      context: ../paper-ebook-admin-be
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3011:3011"
    links:
      - paper-ebook-repository
      - paper-mongodb-crud
  paper-ebook-repository:
    container_name: paper-ebook-repository
    image: latest123/paper-ebook-repository
    volumes:
      - ./data:/data/ebook=repository
    restart: always
    build:
      context: ../paper-ebook-repository
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3012:3012"
  paper-mongodb-crud:
    container_name: paper-mongodb-crud
    image: latest123/paper-mongodb-crud
    restart: always
    build:
      context: ../paper-mongodb-crud
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3015:3015"
    links:
      - mongo
    # environment:
    #   - BLURPAPER_MONGO_SSL_PATH=undefined
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27019:27017'
