version: "3"
services:
  paper-web-app:
    build:
      dockerfile: ./docker/dev/Dockerfile
      args:
        - ENVIRONMENT_NAME=prod
    ports:
      - "8092:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
  paper-web-admin:
    build:
      args:
        - ENVIRONMENT_NAME=prod
  paper-email-templates:
    build:
      dockerfile: ./docker/dev/Dockerfile
      args:
        - ENVIRONMENT_NAME=prod
    ports:
      - "8099:8099"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  # paper-raffle:
  #   build:
  #     context: ../paper-raffle
  #     args:
  #       - ENVIRONMENT_NAME=prod
  paper-order-admin:
    build:
      args:
        - ENVIRONMENT_NAME=prod
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8115:8115"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  paper-ebook-repository:
    build:
      args:
        - ENVIRONMENT_NAME=prod
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
  paper-audiobook-repository:
    build:
      args:
        - ENVIRONMENT_NAME=prod
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - PROTOCOL=https
  paper-email-server:
    build:
      args:
        - ENVIRONMENT_NAME=prod
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - PROTOCOL=https
  paper-be:
    build:
      args:
        - ENVIRONMENT_NAME=prod
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - LINK_TO_PAPER_EMAIL_BE=${PROD_DOMAIN_NAME}
      - PROTOCOL=https
  paper-email-be:
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - LINK_TO_PAPER_LOOP=${PROD_DOMAIN_NAME}
      - PROTOCOL=https
  # paper-raffle-be:
  #   image: latest123/paper-raffle-be
  #   environment:
  #     - NODE_ENV=production
  #     - PRIVATE_KEY=${SSH_PRIVATE_KEY}
  #     - FULL_CHAIN=${SSH_FULL_CHAIN}
  paper-mongodb-crud:
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
  # paper-mongodb-export:
  #   image: latest123/paper-mongodb-export
  #   environment:
  #     - NODE_ENV=production
  #     - PRIVATE_KEY=${SSH_PRIVATE_KEY}
  #     - FULL_CHAIN=${SSH_FULL_CHAIN}
  #     - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
  #     - PROTOCOL=https
  paper-loop:
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - LINK_TO_PAPER_EMAIL_BE=${PROD_DOMAIN_NAME}
      - PROTOCOL=https
  paper-pixel:
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - PROTOCOL=https
  paper-stripe-payment:
    build:
      args:
        - ENVIRONMENT_NAME=prod
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - LINK_TO_GENERIC_PAYMENT=${PROD_DOMAIN_NAME}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - PROTOCOL=https
      - STRIPE_PAYMENT_API_KEY=${PAPER_STRIPE_PAYMENT_BE_PAYMENT_API_KEY_PROD}
  paper-epay-payment:
    build:
      args:
        - ENVIRONMENT_NAME=prod
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - LINK_TO_GENERIC_PAYMENT=${PROD_DOMAIN_NAME}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - PROTOCOL=https
      - EPAY_PAYMENT_URL=${PAPER_EPAY_PAYMENT_BE_PROD_URL}
      - EPAY_MIN=${PAPER_EPAY_PAYMENT_BE_PROD_MIN}
      - EPAY_SECRET=${PAPER_EPAY_PAYMENT_BE_PROD_SECRET}
  paper-epay-notification:
    build:
      args:
        - ENVIRONMENT_NAME=prod
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - LINK_TO_PAPER_BE=${PROD_DOMAIN_NAME}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - PROTOCOL=https
      - EPAY_PAYMENT_URL=${PAPER_EPAY_PAYMENT_BE_PROD_URL}
      - EPAY_MIN=${PAPER_EPAY_PAYMENT_BE_PROD_MIN}
      - EPAY_SECRET=${PAPER_EPAY_PAYMENT_BE_PROD_SECRET}
  paper-generic-payment:
    build:
      args:
        - ENVIRONMENT_NAME=prod
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${SSH_PRIVATE_KEY}
      - LINK_TO_PAPER_CRUD=${PROD_DOMAIN_NAME}
      - FULL_CHAIN=${SSH_FULL_CHAIN}
      - PROTOCOL=https
  paper-cdn:
    ports:
      - '${PAPER_CDN_PORT}:8092'
    volumes:
      - ./data/cdn/nginx-cdn.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  paper-certificate-issuer:
    ports:
      - '${PAPER_CERTIFICATE_ISSUER_PORT}:8092'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  paper-certificate-issuer-cdn:
    ports:
      - '${PAPER_CERTIFICATE_ISSUER_CDN_PORT}:8092'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
