version: "3"
services:
  paper-web-app:
    build:
      dockerfile: ./docker/dev/Dockerfile-dev
    volumes:
      - '../paper/src:/usr/local/app/src'
  paper-ebook-admin-be:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-ebook-admin-be:/usr/src/app/paper-ebook-admin-be
      - /usr/src/app/paper-ebook-admin-be/node_modules
  paper-ebook-repository:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-ebook-repository:/usr/src/app/paper-ebook-repository
      - /usr/src/app/paper-ebook-repository/node_modules
  paper-stripe-payment:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-stripe-payment:/usr/src/app/paper-stripe-payment
      - /usr/src/app/paper-stripe-payment/node_modules
