version: "3"
services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  paper-web-app:
    container_name: paper-web-app
    image: latest123/paper-web-app
    restart: always
    build:
      context: ../paper
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      - APP_NAME=${PAPER_APP_NAME}
  paper-web-admin:
    container_name: paper-admin
    image: latest123/paper-admin
    restart: always
    build:
      context: ../paper-admin
      dockerfile: ./docker/dev/Dockerfile
      args:
        - ENVIRONMENT_NAME=dev
    ports:
      - "8093:80"
      - "8095:8095"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  paper-email-templates:
    container_name: paper-email-templates
    image: latest123/paper-email-templates
    restart: always
    build:
      context: ../paper-email-templates
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  # paper-raffle:
  #   container_name: paper-raffle
  #   image: latest123/paper-raffle
  #   restart: always
  #   build:
  #     context: ../paper-raffle
  #     dockerfile: ./docker/dev/Dockerfile
  #     args:
  #       - ENVIRONMENT_NAME=dev
  #   ports:
  #     - "8101:80"
  #     - "8103:8103"
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  paper-ebook-repository:
    container_name: ${PAPER_EBOOK_REPO_CONTAINER_NAME}
    image: latest123/paper-ebook-repository
    volumes:
      - ./data/paper/repository:/usr/src/app/paper-ebook-repository/digitals
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-ebook-repository/docker/dev/Dockerfile
    ports:
      - ${PAPER_EBOOK_REPO_PORT}:${PAPER_EBOOK_REPO_PORT}
    environment:
      - PORT=${PAPER_EBOOK_REPO_PORT}
      - APP_NAME=${PAPER_EBOOK_REPO_APP_NAME}
  paper-order-admin:
    container_name: paper-order-admin
    image: latest123/paper-order-admin
    restart: always
    build:
      context: ../paper-order-admin
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - '../paper-order-admin/src:/usr/local/app/src'
  paper-audiobook-repository:
    container_name: ${PAPER_AUDIOBOOK_REPO_CONTAINER_NAME}
    image: latest123/paper-audiobook-repository
    volumes:
      - ./data/paper/repository/audio:/usr/src/app/paper-audiobook-repository/digitals/audiobooks
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-audiobook-repository/docker/dev/Dockerfile
    ports:
      - ${PAPER_AUDIOBOOK_REPO_PORT}:${PAPER_AUDIOBOOK_REPO_PORT}
    environment:
      - PORT=${PAPER_AUDIOBOOK_REPO_PORT}
      - APP_NAME=${PAPER_AUDIOBOOK_REPO_APP_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
  paper-email-server:
    container_name: ${PAPER_EMAIL_SERVER_CONTAINER_NAME}
    image: latest123/paper-email-server
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-email-server/docker/dev/Dockerfile
    ports:
      - ${PAPER_EMAIL_SERVER_PORT}:${PAPER_EMAIL_SERVER_PORT}
    environment:
      - PORT=${PAPER_EMAIL_SERVER_PORT}
      - SMTP_PORT=${PAPER_EMAIL_SERVER_SMTP_PORT}
      - APP_NAME=${PAPER_EMAIL_SERVER_APP_NAME}
  paper-be:
    container_name: ${PAPER_BE}
    image: latest123/paper-be
    restart: always
    build:
      context: ../
      dockerfile: ./paper-be/docker/dev/Dockerfile
    ports:
      - ${PAPER_BE_PORT}:${PAPER_BE_PORT}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    environment:
      - PORT=${PAPER_BE_PORT}
      - APP_NAME=${PAPER_BE_APP_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - PAPER_EMAIL_BE_PORT=${PAPER_EMAIL_BE_PORT}
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - LINK_TO_PAPER_EMAIL_BE=${PAPER_EMAIL_BE_CONTAINER_NAME}
      - PROTOCOL=http
      - PAPER_BE_JWT_PRIVATE_KEY=${PAPER_BE_JWT_PRIVATE_KEY}
  paper-email-be:
    container_name: ${PAPER_EMAIL_BE_CONTAINER_NAME}
    image: latest123/paper-email-be
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-email-be/docker/dev/Dockerfile
    ports:
      - ${PAPER_EMAIL_BE_PORT}:${PAPER_EMAIL_BE_PORT}
    environment:
      - PORT=${PAPER_EMAIL_BE_PORT}
      - APP_NAME=${PAPER_EMAIL_BE_APP_NAME}
      - GMAIL_APP_PASSWORD=${PAPER_EMAIL_GMAIL_APP_PASSWORD}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - PAPER_LOOP_PORT=${PAPER_LOOP_PORT}
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - LINK_TO_PAPER_LOOP=${PAPER_LOOP_CONTAINER_NAME}
      - PROTOCOL=http
  # paper-mongodb-export:
  #   container_name: ${PAPER_MONGODB_EXPORT_CONTAINER_NAME}
  #   image: latest123/paper-mongodb-export
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #   restart: always
  #   build:
  #     context: ../
  #     dockerfile: ./paper-mongodb-export/docker/dev/Dockerfile
  #   ports:
  #     - ${PAPER_MONGODB_EXPORT_PORT}:${PAPER_MONGODB_EXPORT_PORT}
  #   environment:
  #     - PORT=${PAPER_MONGODB_EXPORT_PORT}
  #     - APP_NAME=${PAPER_MONGODB_EXPORT_APP_NAME}
  #     - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
  #     - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
  #     - PROTOCOL=http
  # paper-raffle-be:
  #   container_name: ${PAPER_RAFFLE_BE_CONTAINER_NAME}
  #   image: latest123/paper-raffle-be
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #   restart: always
  #   build:
  #     context: ../
  #     dockerfile: ./paper-raffle-be/docker/dev/Dockerfile
  #   ports:
  #     - ${PAPER_RAFFLE_BE_PORT}:${PAPER_RAFFLE_BE_PORT}
  #   environment:
  #     - PORT=${PAPER_RAFFLE_BE_PORT}
  #     - APP_NAME=${PAPER_RAFFLE_BE_APP_NAME}
  paper-loop:
    container_name: ${PAPER_LOOP_CONTAINER_NAME}
    image: latest123/paper-loop
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-loop/docker/dev/Dockerfile
    ports:
      - ${PAPER_LOOP_PORT}:${PAPER_LOOP_PORT}
    environment:
      - PORT=${PAPER_LOOP_PORT}
      - APP_NAME=${PAPER_LOOP_APP_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - PAPER_EMAIL_BE_PORT=${PAPER_EMAIL_BE_PORT}
      - PAPER_LOOP_AUTO_SEND_EMAIL_INTERVAL=${PAPER_LOOP_AUTO_SEND_EMAIL_INTERVAL}
  paper-pixel:
    container_name: ${PAPER_PIXEL_CONTAINER_NAME}
    image: latest123/paper-pixel
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-pixel/docker/dev/Dockerfile
    ports:
      - ${PAPER_PIXEL_PORT}:${PAPER_PIXEL_PORT}
    environment:
      - PORT=${PAPER_PIXEL_PORT}
      - APP_NAME=${PAPER_PIXEL_APP_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - PROTOCOL=http
  paper-stripe-payment:
    container_name: ${PAPER_STRIPE_PAYMENT_BE_CONTAINER_NAME}
    image: latest123/paper-stripe-payment
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-stripe-payment/docker/dev/Dockerfile
    ports:
      - ${PAPER_STRIPE_PAYMENT_BE_PORT}:${PAPER_STRIPE_PAYMENT_BE_PORT}
    environment:
      - PORT=${PAPER_STRIPE_PAYMENT_BE_PORT}
      - APP_NAME=${PAPER_STRIPE_PAYMENT_BE_APP_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - PAPER_GENERIC_PAYMENT_PORT=${PAPER_GENERIC_PAYMENT_BE_PORT}
  paper-epay-payment:
    container_name: ${PAPER_EPAY_PAYMENT_BE_CONTAINER_NAME}
    image: latest123/paper-epay-payment
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-epay-payment/docker/dev/Dockerfile
    ports:
      - ${PAPER_EPAY_PAYMENT_BE_PORT}:${PAPER_EPAY_PAYMENT_BE_PORT}
    environment:
      - PORT=${PAPER_EPAY_PAYMENT_BE_PORT}
      - APP_NAME=${PAPER_EPAY_PAYMENT_BE_APP_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - PAPER_GENERIC_PAYMENT_PORT=${PAPER_GENERIC_PAYMENT_BE_PORT}
  paper-epay-notification:
    container_name: ${PAPER_EPAY_NOTIFICATION_BE_CONTAINER_NAME}
    image: latest123/paper-epay-notification
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-epay-notification/docker/dev/Dockerfile
    ports:
      - ${PAPER_EPAY_NOTIFICATION_BE_PORT}:${PAPER_EPAY_NOTIFICATION_BE_PORT}
    environment:
      - PORT=${PAPER_EPAY_NOTIFICATION_BE_PORT}
      - APP_NAME=${PAPER_EPAY_NOTIFICATION_BE_APP_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - PAPER_BE_PORT=${PAPER_BE_PORT}
  paper-generic-payment:
    container_name: ${PAPER_GENERIC_PAYMENT_BE_CONTAINER_NAME}
    image: latest123/paper-generic-payment
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../
      dockerfile: ./paper-generic-payment/docker/dev/Dockerfile
    ports:
      - ${PAPER_GENERIC_PAYMENT_BE_PORT}:${PAPER_GENERIC_PAYMENT_BE_PORT}
    environment:
      - PORT=${PAPER_GENERIC_PAYMENT_BE_PORT}
      - APP_NAME=${PAPER_GENERIC_PAYMENT_BE_APP_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
  paper-mongodb-crud:
    container_name: ${PAPER_CRUD_CONTAINER_NAME}
    image: latest123/paper-mongodb-crud
    restart: always
    build:
      context: ../
      dockerfile: ./paper-mongodb-crud/docker/dev/Dockerfile
    ports:
      - ${PAPER_CRUD_PORT}:${PAPER_CRUD_PORT}
    links:
      - mongo
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    environment:
      - PORT=${PAPER_CRUD_PORT}
      - APP_NAME=${PAPER_CRUD_APP_NAME}
  paper-cdn:
    container_name: ${PAPER_CDN_CONTAINER_NAME}
    image: nginx:alpine
    restart: always
    volumes:
      - ./data/cdn/:/usr/share/nginx/html
  # To renew the certificate for blurpaper.com
  # Go to 000-default.conf in apache server
  # uncomment the 5025 section
  # comment the below section
  # in the ssh console:
  # - service apache2 stop
  # - service apache2 start
  # - service apache2 restart
  # - bash init-letsencrypt.sh
  # rebuld the docker services
  # in the 000-default.conf comment as the records was in the beggining
  paper-certificate-issuer:
    container_name: ${PAPER_CERTIFICATE_ISSUER_CONTAINER_NAME}
    image: nginx:alpine
    restart: always
    volumes:
      - ./data/cdn/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  paper-certificate-issuer-cdn:
    container_name: ${PAPER_CERTIFICATE_ISSUER_CDN_CONTAINER_NAME}
    image: nginx:alpine
    restart: always
    volumes:
      - ./data/cdn/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/mongo:/data/db
