version: "3"
services:
  paper-web-app:
    build:
      dockerfile: ./docker/dev/Dockerfile-dev
    volumes:
      - '../paper/src:/usr/local/app/src'
    ports:
      - "8090:4200"
  paper-email-templates:
    build:
      dockerfile: ./docker/dev/Dockerfile-dev
    volumes:
      - '../paper-email-templates/src:/usr/local/app/src'
    ports:
      - "8097:4200"
  # paper-order-admin:
  #   build:
  #     dockerfile: ./docker/dev/Dockerfile-dev
  #     args:
  #       - ENVIRONMENT_NAME=dev
  #   volumes:
  #     - '../paper-order-admin/src:/usr/local/app/src'
  #   ports:
  #     - "8113:4200"
  paper-audiobook-admin:
    container_name: paper-audiobook-admin
    image: latest123/paper-audiobook-admin
    restart: always
    build:
      dockerfile: ./docker/dev/Dockerfile-dev
      args:
        - ENVIRONMENT_NAME=dev
      context: ../paper-audiobook-admin
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - '../paper-audiobook-admin/src:/usr/local/app/src'
    ports:
      - "8109:4200"
  paper-ebook-admin:
    container_name: paper-ebook-admin
    image: latest123/paper-ebook-admin
    restart: always
    build:
      context: ../paper-ebook-admin
      dockerfile: ./docker/dev/Dockerfile-dev
      args:
        - ENVIRONMENT_NAME=dev
    ports:
      - "8105:4200"
      - "8107:8099"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - '../paper-ebook-admin/src:/usr/local/app/src'
  paper-ebook-admin-be:
    container_name: ${PAPER_EBOOK_ADMIN_BE_CONTAINER_NAME}
    image: latest123/paper-ebook-admin-be
    restart: always
    build:
      context: ../
      dockerfile: ./paper-ebook-admin-be/docker/dev/Dockerfile
      args:
        - ENVIRONMENT_NAME=dev
    ports:
      - ${PAPER_EBOOK_ADMIN_BE_PORT}:${PAPER_EBOOK_ADMIN_BE_PORT}
    links:
      - ${PAPER_EBOOK_REPO_CONTAINER_NAME}
      - ${PAPER_CRUD_CONTAINER_NAME}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ../paper-ebook-admin-be:/usr/src/app/paper-ebook-admin-be
      - /usr/src/app/paper-ebook-admin-be/node_modules
    environment:
      - PORT=${PAPER_EBOOK_ADMIN_BE_PORT}
      - APP_NAME=${PAPER_EBOOK_ADMIN_BE_APP_NAME}
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - LINK_TO_PAPER_EBOOK_REPO=${PAPER_EBOOK_REPO_CONTAINER_NAME}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - PAPER_EBOOK_REPO_PORT=${PAPER_EBOOK_REPO_PORT}
      - PROTOCOL=http
  paper-ebook-repository:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-ebook-repository:/usr/src/app/paper-ebook-repository
      - /usr/src/app/paper-ebook-repository/node_modules
  paper-audiobook-repository:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-audiobook-repository:/usr/src/app/paper-audiobook-repository
      - /usr/src/app/paper-audiobook-repository/node_modules
    environment:
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
  paper-audiobook-admin-be:
    container_name: ${PAPER_AUDIOBOOK_ADMIN_BE_CONTAINER_NAME}
    image: latest123/paper-audiobook-admin-be
    volumes:
      - ./data/paper/repository/audio:/usr/src/app/paper-audiobook-admin-be/digitals
      - ./data/certbot/conf:/etc/letsencrypt
      - ../paper-audiobook-admin-be:/usr/src/app/paper-audiobook-admin-be
      - /usr/src/app/paper-audiobook-admin-be/node_modules
    restart: always
    build:
      context: ../
      dockerfile: ./paper-audiobook-admin-be/docker/dev/Dockerfile
      args:
        - ENVIRONMENT_NAME=dev
    ports:
      - ${PAPER_AUDIOBOOK_ADMIN_BE_PORT}:${PAPER_AUDIOBOOK_ADMIN_BE_PORT}
    environment:
      - PORT=${PAPER_AUDIOBOOK_ADMIN_BE_PORT}
      - APP_NAME=${PAPER_AUDIOBOOK_ADMIN_BE_APP_NAME}
      - PAPER_AUDIOBOOK_REPO_PORT=${PAPER_AUDIOBOOK_REPO_PORT}
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - LINK_TO_PAPER_AUDIOBOOK_REPO=${PAPER_AUDIOBOOK_REPO_CONTAINER_NAME}
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - PROTOCOL=http
  paper-stripe-payment:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-stripe-payment:/usr/src/app/paper-stripe-payment
      - /usr/src/app/paper-stripe-payment/node_modules
    environment:
      - PROTOCOL=http
      - STRIPE_PAYMENT_API_KEY=${PAPER_STRIPE_PAYMENT_BE_PAYMENT_API_KEY_DEV}
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - LINK_TO_GENERIC_PAYMENT=${PAPER_GENERIC_PAYMENT_BE_CONTAINER_NAME}
  paper-epay-payment:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-epay-payment:/usr/src/app/paper-epay-payment
      - /usr/src/app/paper-epay-payment/node_modules
    environment:
      - PAPER_CRUD_PORT=${PAPER_CRUD_PORT}
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - LINK_TO_GENERIC_PAYMENT=${PAPER_GENERIC_PAYMENT_BE_CONTAINER_NAME}
      - PROTOCOL=http
      - EPAY_PAYMENT_URL=${PAPER_EPAY_PAYMENT_BE_DEV_URL}
      - EPAY_MIN=${PAPER_EPAY_PAYMENT_BE_DEV_MIN}
      - EPAY_SECRET=${PAPER_EPAY_PAYMENT_BE_DEV_SECRET}
  paper-epay-notification:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-epay-notification:/usr/src/app/paper-epay-notification
      - /usr/src/app/paper-epay-notification/node_modules
    environment:
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - LINK_TO_GENERIC_PAYMENT=${PAPER_GENERIC_PAYMENT_BE_CONTAINER_NAME}
      - LINK_TO_PAPER_BE=${PAPER_BE}
      - PROTOCOL=http
      - EPAY_PAYMENT_URL=${PAPER_EPAY_PAYMENT_BE_DEV_URL}
      - EPAY_MIN=${PAPER_EPAY_PAYMENT_BE_DEV_MIN}
      - EPAY_SECRET=${PAPER_EPAY_PAYMENT_BE_DEV_SECRET}
  paper-generic-payment:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-generic-payment:/usr/src/app/paper-generic-payment
      - /usr/src/app/paper-generic-payment/node_modules
    environment:
      - LINK_TO_PAPER_CRUD=${PAPER_CRUD_CONTAINER_NAME}
      - PROTOCOL=http
  paper-cdn:
    ports:
      - ${PAPER_CDN_PORT}:8080
  paper-certificate-issuer:
    ports:
      - ${PAPER_CERTIFICATE_ISSUER_PORT}:8080
  paper-certificate-issuer-cdn:
    ports:
      - ${PAPER_CERTIFICATE_ISSUER_CDN_PORT}:8080
  paper-be:
    build:
      args:
        - ENVIRONMENT_NAME=dev
    volumes:
      - ../paper-be:/usr/src/app/paper-be
      - /usr/src/app/paper-be/node_modules
