version: "3"
services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  paper-web-app:
    container_name: paper-web-app
    image: latest123/paper-web-app
    restart: always
    build:
      context: ../paper
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8090:80"
      - "8092:8092"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  paper-web-admin:
    container_name: paper-admin
    image: latest123/paper-admin
    restart: always
    build:
      context: ../paper-admin
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8093:80"
      - "8095:8095"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  paper-ebook-admin-be:
    container_name: ${PAPER_EBOOK_ADMIN_BE_CONTAINER_NAME}
    image: latest123/paper-ebook-admin-be
    restart: always
    build:
      context: ../paper-ebook-admin-be
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - ${PAPER_EBOOK_ADMIN_BE_PORT}:${PAPER_EBOOK_ADMIN_BE_PORT}
    links:
      - ${PAPER_EBOOK_REPO_CONTAINER_NAME}
      - ${PAPER_CRUD_CONTAINER_NAME}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
  paper-ebook-repository:
    container_name: ${PAPER_EBOOK_REPO_CONTAINER_NAME}
    image: latest123/paper-ebook-repository
    volumes:
      - ./data:/data/ebook=repository
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../paper-ebook-repository
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - ${PAPER_EBOOK_REPO_PORT}:${PAPER_EBOOK_REPO_PORT}
  paper-be:
    container_name: ${PAPER_BE}
    image: latest123/paper-be
    restart: always
    build:
      context: ../paper-be
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - ${PAPER_BE_PORT}:${PAPER_BE_PORT}
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
  paper-email-be:
    container_name: ${PAPER_EMAIL_BE_CONTAINER_NAME}
    image: latest123/paper-ebook-repository
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    build:
      context: ../paper-ebook-repository
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - ${PAPER_EMAIL_BE_PORT}:${PAPER_EMAIL_BE_PORT}
  paper-mongodb-crud:
    container_name: ${PAPER_CRUD_CONTAINER_NAME}
    image: latest123/paper-mongodb-crud
    restart: always
    build:
      context: ../paper-mongodb-crud
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - ${PAPER_CRUD_PORT}:${PAPER_CRUD_PORT}
    links:
      - mongo
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
    # environment:
      # - BLURPAPER_MONGO_SSL_PATH=undefinedd
      # - BLURPAPER_ORIGIN=blurpaper.com
      # - NODE_ENV=production
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data/mongo:/data/db
